Fix a thinko

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -513,10 +513,9 @@ Missing dependency kernel-package, marking for installation.
 Missing dependency kernel-wedge, marking for installation.
 
 "
-    if ! [ "$RELEASE" = "jessie" ]; then
-      apt-get install kernel-wedge --no-install-recommends -y || die "Error installing dependency kernel-wedge"
-    else
-      apt-get -t jessie-backports install kernel-wedge --no-install-recommends -y || die "Error installing dependency kernel-wedge"
+    apt-get install kernel-wedge --no-install-recommends -y || die "Error installing dependency kernel-wedge"
+    if [ "$OS" = "Debian" ]; then
+      apt-get -t $RELEASE-backports install kernel-wedge --no-install-recommends -y > /dev/null 2>&1
     fi
   fi
   if ! dpkg-query -l libdigest-sha-perl | grep "ii" > /dev/null 2>&1; then
