Update for building RC kernels

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -770,11 +770,15 @@ Going to download the kernel source.
   sleep 3
   if [ "x$next_opt" = "xno" ]; then
     if echo "$vanilla_opt" | grep "rc" > /dev/null 2>&1; then
-      wget https://www.kernel.org/pub/linux/kernel/v$MAJOR.x/testing/linux-$vanilla_opt.tar.xz || die "Error(s) while fetching Linux source"
+      wget https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/snapshot/linux-$vanilla_opt.tar.gz || die "Error(s) while fetching Linux source"
     else
       wget https://www.kernel.org/pub/linux/kernel/v$MAJOR.x/linux-$vanilla_opt.tar.xz || die "Error(s) while fetching Linux source"
     fi
-    tar -xJf linux-$vanilla_opt.tar.xz
+    if echo "$vanilla_opt" | grep "rc" > /dev/null 2>&1; then
+      tar -xzf linux-$vanilla_opt.tar.gz
+    else
+      tar -xJf linux-$vanilla_opt.tar.xz
+    fi
     cd linux-$vanilla_opt
     make clean && make mrproper
     if [ "x$debug_opt" = "xyes" ]; then
