Update build-deps for Debian Stretch.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -629,12 +629,12 @@ Missing dependency patchutils, marking for installation.
     apt-get install patchutils --no-install-recommends -y || die "Error installing dependency patchutils"
   fi
   if [ "$RELEASE" = "stretch" ]; then
-    if ! dpkg-query -l g++-5 | grep "ii" > /dev/null 2>&1; then
+    if ! dpkg-query -l g++-6 | grep "ii" > /dev/null 2>&1; then
       echo "
 Missing dependency g++-5, marking for installation.
 
 "
-      apt-get install g++-5 --no-install-recommends -y || die "Error installing dependency g++-5"
+      apt-get install g++-6 --no-install-recommends -y || die "Error installing dependency g++-6"
     fi
   fi
   apt-get build-dep --no-install-recommends linux -y
