Improve fetching Debian/Ubuntu stock kernels

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -333,7 +333,11 @@ fi
 
 # Debian
 if [ "x$stock_opt" = "xyes" ]; then
-  apt-get source linux -y || die "Error(s) while fetching Debian Linux source"
+  if uname -a | egrep 'Debian|Ubuntu' > /dev/null  2>&1; then
+    apt-get source linux-image-`uname -r` -y || die "Error(s) while fetching Debian Linux source"
+  else
+    apt-get source linux -y || die "Error(s) while fetching Debian Linux source"
+  fi
   cd linux-*
   FIRST_DIGIT=$(echo `pwd` | grep -o '[[:digit:]]\+' | head -n1 | awk 'NR==1')
   SECOND_DIGIT=$(echo `pwd` | grep -o '[[:digit:]]\+' | head -n2 | awk 'NR==2')
@@ -551,7 +555,7 @@ cx23885 patch applied.
 
   if [ "x$personal_opt" = "xyes" ];then
     # silabs si2157 si2168 patch
-    if [ "$FIRST_DIGIT" -lt "4" ]; then
+    if [ "$FIRST_DIGIT" -le "4" ]; then
       cp -f ../drivers/media/tuners/* drivers/media/tuners/
       cp -f ../drivers/media/dvb-frontends/* drivers/media/dvb-frontends/
     elif [ "$FIRST_DIGIT" -eq "4" ]; then
