Fix getting stock kernel source

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -333,7 +333,7 @@ fi
 
 # Debian
 if [ "x$stock_opt" = "xyes" ]; then
-  apt-get source linux-image-`uname -r` -y || die "Error(s) while fetching Debian Linux source"
+  apt-get source linux -y || die "Error(s) while fetching Debian Linux source"
   cd linux-*
   FIRST_DIGIT=$(echo `pwd` | grep -o '[[:digit:]]\+' | head -n1 | awk 'NR==1')
   SECOND_DIGIT=$(echo `pwd` | grep -o '[[:digit:]]\+' | head -n2 | awk 'NR==2')
