Add missing uapi patch, update configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -250,30 +250,13 @@ Aborting...
   exit 0
 fi
 
-# Get build-deps, Debian/Ubuntu only.
+# Get build-deps, Debian only.
 if [ -f /usr/bin/lsb_release ]; then
   OS=$( lsb_release -si )
   RELEASE=$( lsb_release -sc )
-  RELEASENUMBER=$(lsb_release -sr | cut -d'.' -f1)
 fi
 
-if [ "$OS" = "Ubuntu" ]; then
-  if ! lsb_release -d | grep LTS > /dev/null 2>&1; then
-    echo "
-Only Ubuntu LTS releases are supported, starting with 14.04 (trusty)
-"
-    exit 1
-  elif [ "$RELEASENUMBER" -lt "14" ]; then
-    echo "
-Only Ubuntu LTS releases are supported, starting with 14.04 (trusty)
-"
-    exit 1
-  else
-    UBUNTURELEASE="LTS"
-  fi
-fi
-
-if ! [ "$OS" = "Debian" -o "$OS" = "Ubuntu" ] ; then
+if ! [ "$OS" = "Debian" ] ; then
   stock_opt=no
 else
   if ! dpkg-query -l build-essential | grep "ii" > /dev/null 2>&1; then
@@ -301,11 +284,7 @@ Aborting...
 "
     exit 1
   fi
-  if [ "$OS" = "Debian" ]; then
-    apt-get install linux-headers-amd64
-  elif [ "$OS" = "Ubuntu" ]; then
-    apt-get install linux-headers-generic
-  fi
+  apt-get install linux-headers-amd64
   if ! [ "$?" -eq "0" ]; then
     echo "
 Error(s) while installing build dependencies
@@ -314,12 +293,12 @@ Aborting...
 "
     exit 1
   fi
-  if ! [ "$RELEASE" = "jessie" -o "$UBUNTURELEASE" = "LTS" ];then
+  if ! [ "$RELEASE" = "jessie" ];then
     if [ "x$stock_opt" = "xyes" ]; then
       echo "
 Recompiling a stock kernel is only supported in
 
-Debian Stable (Jessie) or Ubuntu LTS, starting with trusty.
+Debian Stable (Jessie)
 
 You can choose to compile a vanilla kernel or the v4l tree.
 
@@ -346,13 +325,8 @@ fi
 
 # Debian
 if [ "x$stock_opt" = "xyes" ]; then
-  if [ "$OS" = "Debian" ]; then
-    apt-get -t jessie source linux -y || die "Error(s) while fetching Debian Linux source"
-    cd linux-*
-  elif [ "$OS" = "Ubuntu" ]; then
-    apt-get source linux -y || die "Error(s) while fetching Ubuntu Linux source"
-    cd linux-*
-  fi
+  apt-get -t jessie source linux -y || die "Error(s) while fetching Debian Linux source"
+  cd linux-*
 fi
 
 # v4l
@@ -361,25 +335,31 @@ if [ "x$v4l_opt" = "xyes" ];then
   git clone --depth=1 git://linuxtv.org/media_tree.git || die "Error(s) while fetching v4l source tree"
 fi
 
-# Other
+# Vanilla
 if [ "x$vanilla_opt" != "x" ];then
   MAJOR=$(echo "$vanilla_opt" | cut -d'.' -f1)
   VERSION=$( echo "$vanilla_opt" | cut -d'.' -f2 | cut -d'-' -f1 )
-  if [ "$MAJOR" -lt "3" ]; then
-    echo "
-Minimum supported kernel version is linux-3.10.x
-You requested linux-$vanilla_opt
+  MINVERSION="18"
+  # Check for minimum supported kernel version to build with
+  # (should be 3.18 or up)
+  if [ "$MAJOR" -lt "4" ]; then
+    if ! [ "$VERSION" -eq "10" ]; then
+      if [ "$VERSION" -lt "$MINVERSION" ]; then
+        echo -en "
+\E[1;33;44m
+This TBS6281/6285 driver is supported intree as of 3.18.x kernels.
+
+(With the exeption of 3.10.x kernels)
+
+You requested a build with a $vanilla_opt kernel.
+
 Aborting...
+\E[0m
+
 "
-    exit 1
-  fi
-  if [ "$MAJOR" -eq "3" ] && [ "$VERSION" -lt "10" ]; then
-    echo "
-Minimum supported kernel version is linux-3.10.x
-You requested linux-$vanilla_opt
-Aborting...
-"
-    exit 1
+        exit 0
+      fi
+    fi
   fi
   if ! echo "$vanilla_opt" | grep "rc" > /dev/null 2>&1; then
     wget https://www.kernel.org/pub/linux/kernel/v$MAJOR.x/linux-$vanilla_opt.tar.xz || die "Error(s) while fetching Linux source"
@@ -395,33 +375,104 @@ fi
 # Patch the source
 #
 
-# Common
+# Common (stock and vanilla kernels)
 if [ "x$v4l_opt" = "xno" ]; then
+  FIRST_DIGIT=$(echo `pwd` | grep -o '[[:digit:]]\+' | head -n1 | awk 'NR==1')
+  SECOND_DIGIT=$(echo `pwd` | grep -o '[[:digit:]]\+' | head -n2 | awk 'NR==2')
+
+  # dvbloopback patch
   mkdir drivers/media/pci/dvbloopback
   cp -f ../dvbloopback/* drivers/media/pci/dvbloopback/
   patch -p0 < ../dvbloopback.patch
-  FIRST_DIGIT=$( echo `pwd` | grep -o '[[:digit:]]\+' | head -n2 | awk 'NR==2' )
-  SECOND_DIGIT=$( echo `pwd` | grep -o '[[:digit:]]\+' | head -n3 | awk 'NR==3' )
   if [ "$FIRST_DIGIT" -lt "4" ] && [ "$SECOND_DIGIT" -lt "13" ]; then
     patch -p0 < ../3.7-dvb-core.patch
   else
     patch -p0 < ../3.13-dvb-core.patch
   fi
+
+  # saa716x patch, also contains gapped clock patch
+  mkdir drivers/media/pci/saa716x
+  cp -f ../drivers/media/pci/saa716x/* drivers/media/pci/saa716x/
+  if ! [ "$VERSION" = "10" ]; then
+    patch -p0 < ../Kconfig.patch
+  else
+    patch -p0 < ../Kconfig-3.10.patch
+  fi
+  if [ "$SECOND_DIGIT" = "16" ]; then
+    patch -p0 < ../Makefile-3.16.patch
+  elif [ "$SECOND_DIGIT" = "10" ]; then
+    patch -p0 < ../Makefile-3.10.patch
+  else
+    patch -p0 < ../Makefile.patch
+  fi
+  patch -p0 < ../uapi.patch
+
+  # cx23885 patch, also contains gapped clock patch
+  if [ "$FIRST_DIGIT" -lt "4" ]; then
+    if [ "$SECOND_DIGIT" = "19" ]; then
+      patch -p0 < ../cx23885-3.19.patch
+    elif [ "$SECOND_DIGIT" = "18" ]; then
+      patch -p0 < ../cx23885-3.18.patch
+    elif [ "$SECOND_DIGIT" = "16" ]; then
+      patch -p0 < ../cx23885-3.16.patch
+    elif [ "$SECOND_DIGIT" = "10" ]; then
+      patch -p0 < ../cx23885-3.10.patch
+    fi
+  else
+    patch -p0 < ../cx23885-4.0.patch
+  fi
+
+  # silabs si2157 si2168 patch, also contains gapped clock patch
+  cp -f ../drivers/media/tuners/* drivers/media/tuners/
+  cp -f ../drivers/media/dvb-frontends/* drivers/media/dvb-frontends/
+
+  # silabs si2168 DVB-C patch
+  sed -i 's/SYS_DVBT, SYS_DVBT2, SYS_DVBC_ANNEX_A/SYS_DVBC_ANNEX_A/' drivers/media/dvb-frontends/si2168.c
+
+  # If linux source >= 4.2 patch saa716x with IF patch
+  #if [ "$FIRST_DIGIT" -eq "4" ] && [ "$SECOND_DIGIT" -gt "1" ]; then
+  #  patch -p0 < ../saa716x_IF.patch
+  #fi
 fi
 
 # v4l
 if [ "x$v4l_opt" = "xyes" ]; then
   cd media_tree
+
+  # dvbloopback patch
   mkdir drivers/media/pci/dvbloopback
   cp -f ../dvbloopback/* drivers/media/pci/dvbloopback/
   patch -p0 < ../dvbloopback.patch
   patch -p0 < ../3.13-dvb-core.patch
+
+  # saa716x patch, also contains gapped clock patch
+  mkdir drivers/media/pci/saa716x
+  cp -f ../drivers/media/pci/saa716x/* drivers/media/pci/saa716x/
+  patch -p0 < ../Kconfig.patch
+  patch -p0 < ../Makefile.patch
+
+  # silabs si2168 gapped clock patch
+  cp -f ../drivers/media/tuners/* drivers/media/tuners/
+  cp -f ../drivers/media/dvb-frontends/* drivers/media/dvb-frontends/
+
+  # silabs si2168 DVC-C patch
+  sed -i 's/SYS_DVBT, SYS_DVBT2, SYS_DVBC_ANNEX_A/SYS_DVBC_ANNEX_A/' drivers/media/dvb-frontends/si2168.c
+
+  # cx23885 gapped clock patch
+  patch -p0 < ../cx23885-4.0.patch
+
+  # commit patches
   git add -A
-  git commit -a -m 'Add dvbloopback driver, patch dvb-core.'
+  git commit -a -m 'Add drivers, patch dvb-core and si2168.'
+
+
   cd ../media_build
+
+  # make install patch
   patch -p0 < ../v4l-make-install.patch
+
+  # commit patch
   git commit -a -m 'Install drivers in /lib/modules/`uname -r`/updates/media'
-  make dir DIR=../media_tree
 fi
 
 #
@@ -430,128 +481,142 @@ fi
 
 # Debian
 if [ "x$stock_opt" = "xyes" ]; then
-  if [ "$OS" = "Debian" ]; then
-    if [ "$abi_opt" = "900" ]; then
-      DEBIANKERNEL=$(echo `pwd` | grep -o '[[:digit:]]\+\.[[:digit:]]\+')
-      RUNNING=$(uname -r | grep "90[0-9]-amd64")
-      if [ -d /lib/modules/$DEBIANKERNEL.0-900-amd64 ]; then
-        if ! [ -d /lib/modules/$DEBIANKERNEL.0-901-amd64 ]; then
-          abi_opt=901
-        elif ! [ -d /lib/modules/$DEBIANKERNEL.0-902-amd64 ]; then
-          abi_opt=902
-        elif ! [ -d /lib/modules/$DEBIANKERNEL.0-903-amd64 ]; then
-          abi_opt=903
-        elif ! [ -d /lib/modules/$DEBIANKERNEL.0-904-amd64 ]; then
-          abi_opt=904
-        elif ! [ -d /lib/modules/$DEBIANKERNEL.0-905-amd64 ]; then
-          abi_opt=905
-        elif ! [ -d /lib/modules/$DEBIANKERNEL.0-906-amd64 ]; then
-          abi_opt=906
-        elif ! [ -d /lib/modules/$DEBIANKERNEL.0-907-amd64 ]; then
-          abi_opt=907
-        elif ! [ -d /lib/modules/$DEBIANKERNEL.0-908-amd64 ]; then
-          abi_opt=908
-        elif ! [ -d /lib/modules/$DEBIANKERNEL.0-909-amd64 ]; then
-          abi_opt=909
-        else
-          if [ "$RUNNING" = "" ]; then
-            echo "
+  if [ "$abi_opt" = "900" ]; then
+    DEBIANKERNEL=$(echo `pwd` | grep -o '[[:digit:]]\+\.[[:digit:]]\+')
+    RUNNING=$(uname -r | grep "90[0-9]-amd64")
+    if [ -d /lib/modules/$DEBIANKERNEL.0-900-amd64 ]; then
+      if ! [ -d /lib/modules/$DEBIANKERNEL.0-901-amd64 ]; then
+        abi_opt=901
+      elif ! [ -d /lib/modules/$DEBIANKERNEL.0-902-amd64 ]; then
+        abi_opt=902
+      elif ! [ -d /lib/modules/$DEBIANKERNEL.0-903-amd64 ]; then
+        abi_opt=903
+      elif ! [ -d /lib/modules/$DEBIANKERNEL.0-904-amd64 ]; then
+        abi_opt=904
+      elif ! [ -d /lib/modules/$DEBIANKERNEL.0-905-amd64 ]; then
+        abi_opt=905
+      elif ! [ -d /lib/modules/$DEBIANKERNEL.0-906-amd64 ]; then
+        abi_opt=906
+      elif ! [ -d /lib/modules/$DEBIANKERNEL.0-907-amd64 ]; then
+        abi_opt=907
+      elif ! [ -d /lib/modules/$DEBIANKERNEL.0-908-amd64 ]; then
+        abi_opt=908
+      elif ! [ -d /lib/modules/$DEBIANKERNEL.0-909-amd64 ]; then
+        abi_opt=909
+      else
+        if [ "$RUNNING" = "" ]; then
+          echo "
 
 You have a total of 10 \"$DEBIANKERNEL.0-90x-amd64\" kernels installed.
 Not going to install any more of those, aborting...
 "
-            exit 0
-          else
-            echo  "
+          exit 0
+        else
+          echo  "
 
 You have a total of 10 \"$DEBIANKERNEL.0-90x-amd64\" kernels installed.
 You are currently running the $RUNNING version of those.
 Not going to install any more of those, aborting...
 "
-            exit 0
-          fi 
-        fi
+          exit 0
+        fi 
       fi
     fi
-    _ABINAME=$(cat debian/config/defines | grep 'abiname:' | awk -F"[ ]" '{ print $NF }')
-    export _ABINAME
-    sed -i "s/abiname: $_ABINAME/abiname: $abi_opt/" debian/config/defines
-    sed -i "s/-$_ABINAME/-$abi_opt/g" debian/rules.gen
-    fakeroot debian/rules debian/control-real
-    sed -i "s/DEBUG='True'/DEBUG='FALSE'/g" debian/rules.gen
-    fakeroot make -f debian/rules.gen setup_amd64_none_amd64
-    sed -i "s/CONFIG_DVB_MAX_ADAPTERS=8/CONFIG_DVB_MAX_ADAPTERS=$adapters_opt/" debian/build/build_amd64_none_amd64/.config
-  elif [ "$OS" = "Ubuntu" ]; then
-    chmod a+x debian/scripts/*
-    chmod a+x debian/scripts/misc/*
-    sed -i "s/CONFIG_DVB_MAX_ADAPTERS=8/CONFIG_DVB_MAX_ADAPTERS=$adapters_opt/" debian.master/config/config.common.ubuntu
-    sed -i "/CONFIG_DVB_LNBP22=m/a CONFIG_DVB_LOOPBACK_ADAPTER=m/" debian.master/config/config.common.ubuntu
-    fakeroot debian/rules updateconfigs amd64
-    UBUNTUKERNEL=$(echo `pwd` | grep -o '[[:digit:]]\+\.[[:digit:]]\+')
-    _ABIDIR=$(ls debian.master/abi/)    
-    _ABINAME=$(ls debian.master/abi/ | grep -o '[[:digit:]]\+' | head -n4 | awk 'NR==4')
-    if [ "$abi_opt" = "900" ]; then
-      RUNNING=$(uname -r | grep "90[0-9]-generic")
-      if [ -d /lib/modules/$UBUNTUKERNEL.0-900-generic ]; then
-        if ! [ -d /lib/modules/$UBUNTUKERNEL.0-901-generic ]; then
-          abi_opt=901
-        elif ! [ -d /lib/modules/$UBUNTUKERNEL.0-902-generic ]; then
-          abi_opt=902
-        elif ! [ -d /lib/modules/$UBUNTUKERNEL.0-903-generic ]; then
-          abi_opt=903
-        elif ! [ -d /lib/modules/$UBUNTUKERNEL.0-904-generic ]; then
-          abi_opt=904
-        elif ! [ -d /lib/modules/$UBUNTUKERNEL.0-905-generic ]; then
-          abi_opt=905
-        elif ! [ -d /lib/modules/$UBUNTUKERNEL.0-906-generic ]; then
-          abi_opt=906
-        elif ! [ -d /lib/modules/$UBUNTUKERNEL.0-907-generic ]; then
-          abi_opt=907
-        elif ! [ -d /lib/modules/$UBUNTUKERNEL.0-908-generic ]; then
-          abi_opt=908
-        elif ! [ -d /lib/modules/$UBUNTUKERNEL.0-909-generic ]; then
-          abi_opt=909
-        else
-          if [ "$RUNNING" = "" ]; then
-            echo "
-
-You have a total of 10 \"$UBUNTUKERNEL.0-90x-generic\" kernels installed.
-Not going to install any more of those, aborting...
-"
-            exit 0
-          else
-            echo  "
-
-You have a total of 10 \"$UBUNTUKERNEL.0-90x-generic\" kernels installed.
-You are currently running the $RUNNING version of those.
-Not going to install any more of those, aborting...
-"
-            exit 0
-          fi 
-        fi
-      fi
-    fi
-    _NEWABIDIR=$(echo $_ABIDIR | sed "s/$_ABINAME/$abi_opt/")
-    sed -i "s/$UBUNTUKERNEL.0-$_ABINAME/$UBUNTUKERNEL.0-$abi_opt/g" debian/control
-    sed -i "s/$UBUNTUKERNEL.0-$_ABINAME/$UBUNTUKERNEL.0-$abi_opt/g" debian/control.stub
-    sed -i "s/$UBUNTUKERNEL.0-$_ABINAME/$UBUNTUKERNEL.0-$abi_opt/g" debian/changelog
-    sed -i "s/$UBUNTUKERNEL.0-$_ABINAME/$UBUNTUKERNEL.0-$abi_opt/g" debian.master/changelog
-    mv debian.master/abi/$_ABIDIR debian.master/abi/$_NEWABIDIR
-    fakeroot debian/rules clean
   fi
+  _ABINAME=$(cat debian/config/defines | grep 'abiname:' | awk -F"[ ]" '{ print $NF }')
+  export _ABINAME
+  sed -i "s/abiname: $_ABINAME/abiname: $abi_opt/" debian/config/defines
+  sed -i "s/-$_ABINAME/-$abi_opt/g" debian/rules.gen
+  fakeroot debian/rules debian/control-real
+  sed -i "s/DEBUG='True'/DEBUG='FALSE'/g" debian/rules.gen
+  fakeroot make -f debian/rules.gen setup_amd64_none_amd64
+  sed -i "s/CONFIG_DVB_MAX_ADAPTERS=8/CONFIG_DVB_MAX_ADAPTERS=$adapters_opt/" debian/build/build_amd64_none_amd64/.config
 fi
 
 # v4l
 if [ "x$v4l_opt" = "xyes" ]; then
+  make dir DIR=../media_tree
   make distclean
   make allyesconfig
   sed -i "s/CONFIG_DVB_MAX_ADAPTERS=8/CONFIG_DVB_MAX_ADAPTERS=$adapters_opt/" v4l/.config
   sed -i "s/CONFIG_MEDIA_CONTROLLER_DVB=y/# CONFIG_MEDIA_CONTROLLER_DVB is not set/" v4l/.config
 fi
 
-# Other
+# Vanilla
 if [ "x$stock_opt" = "xno" ]; then
-  make oldconfig
+  echo -en "
+Going to configure your vanilla kernel.
+
+"
+  if [ "$MAJOR" -lt "4" ]; then
+    if [ "$VERSION" = "19" ]; then
+      echo -en "
+Choise: use supplied config file or
+do 'make oldconfig'. Do you want to
+use supplied kernel config?
+If you hit 'n', 'make oldconfig' starts.
+
+"
+      confirmyes "Yes, use it. [Y/n]"
+
+      if [ "$?" -eq 0 ]; then
+        cp -f ../kernelconfig/amd64/3.19/config ./.config
+      else
+        make oldconfig
+      fi
+    elif [ "$VERSION" = "18" ]; then
+      echo -en "
+Choise: use supplied config file or
+do 'make oldconfig'. Do you want to
+use supplied kernel config?
+If you hit 'n', 'make oldconfig' starts.
+
+"
+      confirmyes "Yes, use it. [Y/n]"
+
+      if [ "$?" -eq 0 ]; then
+        cp -f ../kernelconfig/amd64/3.18/config ./.config
+      else
+        make oldconfig
+      fi
+    elif [ "$VERSION" = "10" ]; then
+      echo -en "
+Choise: use supplied config file or
+do 'make oldconfig'. Do you want to
+use supplied kernel config?
+If you hit 'n', 'make oldconfig' starts.
+
+"
+      confirmyes "Yes, use it. [Y/n]"
+
+      if [ "$?" -eq 0 ]; then
+        cp -f ../kernelconfig/amd64/3.10/config ./.config
+      else
+        make oldconfig
+      fi
+    fi
+  elif [ "$MAJOR" -lt "5" ]; then
+    if [ "$VERSION" = "0" ]; then
+      echo -en "
+Choise: use supplied config file or
+do 'make oldconfig'. Do you want to
+use supplied kernel config?
+If you hit 'n', 'make oldconfig' starts.
+
+"
+      confirmyes "Yes, use it. [Y/n]"
+
+      if [ "$?" -eq 0 ]; then
+        cp -f ../kernelconfig/amd64/4.0/config ./.config
+      else
+        make oldconfig
+      fi
+    else
+      make oldconfig
+    fi
+  else    
+    make oldconfig
+  fi
   ADAPTERS=$( cat .config | grep "CONFIG_DVB_MAX_ADAPTERS" | grep -o '[[:digit:]]\+' )
   if ! [ "$ADAPTERS" = "$adapters_opt" ]; then
     sed -i "s/CONFIG_DVB_MAX_ADAPTERS=$ADAPTERS/CONFIG_DVB_MAX_ADAPTERS=$adapters_opt/" .config
@@ -567,33 +632,18 @@ fi
 
 # Debian
 if [ "x$stock_opt" = "xyes" ]; then
-  if [ "$OS" = "Debian" ]; then
-    fakeroot make -f debian/rules.gen binary-arch_amd64_none_real
-    fakeroot make -f debian/rules.gen binary-arch_amd64_none_amd64
-    if ! [ "$?" -eq "0" ]; then
-      echo "
+  fakeroot make -f debian/rules.gen binary-arch_amd64_none_real
+  fakeroot make -f debian/rules.gen binary-arch_amd64_none_amd64
+  if ! [ "$?" -eq "0" ]; then
+    echo "
 Error(s) while compiling the kernel
 
 Aborting...
 "
-      exit 1
-    fi
-    cd ..
-    rm -f xen*
-  elif [ "$OS" = "Ubuntu" ]; then
-    AUTOBUILD=1 NOEXTRAS=1 skipabi=true fakeroot debian/rules binary-headers binary-generic
-    if ! [ "$?" -eq "0" ]; then
-      echo "
-Error(s) while compiling the kernel
-
-Aborting...
-"
-      exit 1
-    fi
-    cd ..
-    rm -f linux-tools*
-    rm -f linux-cloud*
+    exit 1
   fi
+  cd ..
+  rm -f xen*
 fi
 
 # v4l
@@ -613,8 +663,20 @@ Aborting...
   fi
 fi
 
-# Other
+# Vanilla
+if [ "x$v4l_opt" = "xno" ] && [ "x$stock_opt" = "xno" ]; then
+  make-kpkg --rootcmd fakeroot clean
+  make-kpkg --rootcmd fakeroot --initrd kernel_image kernel_headers
+  if ! [ "$?" -eq "0" ]; then
+    echo "
+Error(s) while compiling the kernel
 
+Aborting...
+"
+    exit 1
+  fi
+  cd ..
+fi
 
 #
 # Install the result
@@ -622,10 +684,9 @@ fi
 
 # Debian
 if [ "x$stock_opt" = "xyes" ]; then
-  if [ "$OS" = "Debian" ]; then
-    dpkg -i *.deb
-    apt-get -f install
-    echo "
+  dpkg -i *.deb
+  apt-get -f install
+  echo "
 Installed:
 
 linux-image-$DEBIANKERNEL.0-$abi_opt-amd64
@@ -635,31 +696,40 @@ linux-headers-$DEBIANKERNEL.0-$abi_opt-common
 All done, you should reboot NOW!
 
 "
-  elif [ "$OS" = "Ubuntu" ]; then
-    dpkg -i *.deb
-    apt-get -f install
-    echo "
-Installed:
-
-linux-image-$UBUNTUKERNEL.0-$abi_opt-generic
-linux-image-extra-$UBUNTUKERNEL.0-$abi_opt-generic
-linux-headers-$UBUNTUKERNEL.0-$abi_opt-generic
-linux-headers-$UBUNTUKERNEL.0-$abi_opt
-
-All done, you should reboot NOW!
-
-"
-  fi
 fi
 
 # v4l
 if [ "x$v4l_opt" = "xyes" ]; then
-  if [ -d /lib/modules/`uname -r`/updates/media ]; then
-    rm -rf /lib/modules/`uname -r`/updates/media
-    depmod -a
+  confirmno "
+v4l source is compiled. Install it? [N/y]
+"
+  if [ "$?" = "0" ]; then
+    if [ -d /lib/modules/`uname -r`/updates/media ]; then
+      rm -rf /lib/modules/`uname -r`/updates/media
+      depmod -a
+    fi
+    make install
   fi
-  make install
 fi
 
-# Other
-
+# Vanilla
+if [ "x$v4l_opt" = "xno" ] && [ "x$stock_opt" = "xno" ]; then
+  dpkg -i *.deb
+  if echo $vanilla_opt | grep "rc" > /dev/null 2>&1; then
+    BUILDLINK="/lib/modules/$(ls -d1 */ | grep "linux" | sed 's/linux-//' | sed 's/-rc/.0-rc/')build"
+    SOURCELINK="/lib/modules/$(ls -d1 */ | grep "linux" | sed 's/linux-//' | sed 's/-rc/.0-rc/')source"
+    HEADERSDIR="/usr/src/$(ls -d1 */ | grep "linux" | sed 's/linux-/linux-headers-/' | sed 's/-r/.0-r/' | sed 's/\///')"
+  elif echo $vanilla_opt | grep -o '[[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+' > /dev/null 2>&1; then
+    BUILDLINK="/lib/modules/$(ls -d1 */ | grep "linux" | sed 's/linux-//')build"
+    SOURCELINK="/lib/modules/$(ls -d1 */ | grep "linux" | sed 's/linux-//')source"
+    HEADERSDIR="/usr/src/$(ls -d1 */ | grep "linux" | sed 's/linux-/linux-headers-/' | sed 's/\///')"
+  else
+    BUILDLINK="/lib/modules/$(ls -d1 */ | grep "linux" | sed 's/linux-//' | sed 's/\//.0\//')build"
+    SOURCELINK="/lib/modules/$(ls -d1 */ | grep "linux" | sed 's/linux-//' | sed 's/\//.0\//')source"
+    HEADERSDIR="/usr/src/$(ls -d1 */ | grep "linux" | sed 's/linux-/linux-headers-/' | sed 's/\//.0/')"
+  fi
+  rm -f $BUILDLINK
+  rm -f $SOURCELINK
+  ln -s $HEADERSDIR $SOURCELINK
+  ln -s $HEADERSDIR $BUILDLINK
+fi
