Use gcc v5 on Stretch

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -603,6 +603,15 @@ Missing dependency patchutils, marking for installation.
 "
     apt-get install patchutils --no-install-recommends -y || die "Error installing dependency patchutils"
   fi
+  if [ "$RELEASE" = "stretch" ]; then
+    if ! dpkg-query -l g++-5 | grep "ii" > /dev/null 2>&1; then
+      echo "
+Missing dependency g++-5, marking for installation.
+
+"
+      apt-get install g++-5 --no-install-recommends -y || die "Error installing dependency g++-5"
+    fi
+  fi
   apt-get build-dep --no-install-recommends linux -y
   if ! [ "$?" -eq "0" ]; then
     echo "
@@ -1364,6 +1373,7 @@ fi
 
 # Vanilla
 if [ "x$vanilla_opt" != "x" ]; then
+  ../gcc-version 5
   make-kpkg --rootcmd fakeroot clean
   if [ "x$debug_opt" = "xno" ]; then
     export CONCURRENCY_LEVEL=2
@@ -1383,10 +1393,12 @@ Error(s) while compiling the kernel
 
 Aborting...
 "
+    ../gcc-version 6
     env_clean
     exit 1
   fi
   cd ..
+  gcc-version 6
 fi
 
 #
