Improve installation of build deps

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -466,13 +466,6 @@ Missing dependency bison, marking for installation.
 "
     apt-get install bison --no-install-recommends -y || die "Error installing dependency bison"
   fi
-  if ! dpkg-query -l crash | grep "ii" > /dev/null 2>&1; then
-    echo "
-Missing dependency crash, marking for installation.
-
-"
-    apt-get install crash --no-install-recommends -y || die "Error installing dependency crash"
-  fi
   if ! dpkg-query -l devscripts | grep "ii" > /dev/null 2>&1; then
     echo "
 Missing dependency devscripts, marking for installation.
@@ -520,10 +513,11 @@ Missing dependency kernel-package, marking for installation.
 Missing dependency kernel-wedge, marking for installation.
 
 "
-    apt-get install kernel-wedge --no-install-recommends -y || die "Error installing dependency kernel-wedge"
-  fi
-  if [ "$RELEASE" = "jessie" ]; then
-    apt-get -t jessie-backports install kernel-wedge --no-install-recommends -y > /dev/null 2>&1
+    if ! [ "$RELEASE" = "jessie" ]; then
+      apt-get install kernel-wedge --no-install-recommends -y || die "Error installing dependency kernel-wedge"
+    else
+      apt-get -t jessie-backports install kernel-wedge --no-install-recommends -y > /dev/null 2>&1
+    fi
   fi
   if ! dpkg-query -l libdigest-sha-perl | grep "ii" > /dev/null 2>&1; then
     echo "
